### ISSUE TITLE
Free chest when dying on another death chest

### ISSUE THREAD

**Issue by DanSleeman** [XHawk87/DeathChests#10]
It seems like when you die on top of an existing death chest, the new chest breaks the existing one, but makes it droppable again.

This then gets sucked into the new death chest with the rest of the contents.

**Comment by XHawk87** [comment]
It can be pretty difficult to break death chests with other death chests now as it will attempt to pick a free block nearby. Are you using the latest version?

The method it uses to prevent them from dropping is to detect chest items floating that have the Death Chest title on them and remove them, so unless ```setblock``` is removing this metadata when it drops items, this shouldn't be the case. If it is, it points to a bug in Minecraft. 

What versions of DeathChests and Minecraft are you using, by the way?

**Comment by XHawk87** [comment]
I've confirmed the issue is a bug in Minecraft and reported it on their bug tracker: ~~https://bugs.mojang.com/browse/MC-136947~~

Edit: There is another issue for it already open: https://bugs.mojang.com/browse/MC-124926

Follow the link and vote if you want Mojang to fix it
